services:
  frontend:
    image: todo-frontend
    build: ./todo-frontend/
    volumes:
      - ./todo-frontend/:/usr/src/app
    ports:
      - 80:80
    networks:
      - todo-network

  backend:
    image: todo-backend
    build: ./todo-backend/
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongodb:27017/the_database
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
    volumes:
      - ./todo-backend:/src
    depends_on:
      - mongodb
      - redis
    networks:
      - todo-network

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    depends_on:
      - backend
      - frontend
    networks:
      - todo-network

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - ./todo-backend/mongo_data:/data/db
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - todo-network

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
