services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - ./mongo_data:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - node-network

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis_data:/data
    networks:
      - node-network

  backend:
    image: todo-backend
    build: .
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongodb:27017/the_database
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
    volumes:
      - .:/src
    depends_on:
      - mongodb
      - redis
    networks:
      - node-network

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    depends_on:
      - backend
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
